// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  return {
    routes: {"1":{"path":"/","redirect":"/home","parentId":"ant-design-pro-layout","id":"1"},"2":{"name":"登录","path":"/login","layout":false,"file":"@/pages/Login/index.tsx","id":"2"},"3":{"name":"首页","path":"/home","meta":{"icon":"home"},"file":"@/pages/Home/index.tsx","parentId":"ant-design-pro-layout","id":"3"},"4":{"name":"智能表单","path":"/SmartForms","file":"@/pages/SmartForms/index.tsx","parentId":"ant-design-pro-layout","id":"4"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","file":"@/.umi-production/plugin-layout/Layout.tsx","isLayout":true}},
    routeComponents: {
'1': React.lazy(() => import( './EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__Login__index" */'@/pages/Login/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__Home__index" */'@/pages/Home/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__SmartForms__index" */'@/pages/SmartForms/index.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "t__plugin-layout__Layout" */'@/.umi-production/plugin-layout/Layout.tsx')),
},
  };
}
