// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export {
  proxy, useSnapshot, snapshot, subscribe,
  proxyWithComputed,
  proxyWithHistory,
  proxyWithDevtools,
  proxyMap,
  proxySet,
} from 'E:/Study/REACT/catgroundfa-react/node_modules/.pnpm/@umijs+valtio@1.0.0_react@18.2.0/node_modules/@umijs/valtio';
